const webpackMerge = require('webpack-merge');
const nodeExternals = require('webpack-node-externals');

const commonConfig = require('./config/webpack.common.js');

module.exports = webpackMerge(
    commonConfig, {
        externals: [
            nodeExternals({
                whitelist: [
                    'jquery',
                    'moment',
                    '@angular/platform-browser',
                    '@angular/platform-browser-dynamic',
                    '@angular/animations',
                    '@angular/core',
                    '@angular/common',
                    '@angular/common/http',
                    '@angular/compiler',
                    '@angular/forms',
                    '@angular/http',
                    '@angular/platform-browser',
                    '@angular/platform-browser-dynamic',
                    '@angular-devkit/build-webpack',
                    '@angular/router',
                    'rxjs',
                    'rxjs/operators',
                    'base64-js',
                    'core-util-is',
                    'debug',
                    'diff',
                    'escape-string-regexp',
                    'glob',
                    'growl',
                    'he',
                    'mkdirp',
                    'ms',
                    'ieee754',
                    'string_decoder',
                    'supports-color',
                    'util',
                    'browser-stdout',
                    'buffer',
                    'isarray',
                    'stream-browserify',
                    'readable-stream',
                    'readable-stream/readable.js',
                    'readable-stream/writable.js',
                    'readable-stream/duplex.js',
                    'readable-stream/transform.js',
                    'readable-stream/passthrough.js',
                    'marked/lib/marked.js',
                    'prismjs/prism.js',
                    'prismjs/components/prism-css.min.js',
                    'prismjs/components/prism-javascript.min.js',
                    'prismjs/components/prism-markdown.min.js',
                    'core-js',
                    'events',
                    'highlightjs',
                    'inherits',
                    'jsdom',
                    'knockout',
                    'knockout-daterangepicker-fb',
                    'marked',
                    'mocha',
                    'ngx-markdown',
                    'ngx-md',
                    'process',
                    'assertion-error',
                    'check-error',
                    'deep-eql',
                    'get-func-name',
                    'pathval',
                    'type-detect',
                    'chai',
                    'chai/utils',
                    'chai/core',
                    'chai/interface',
                    'chai/chai.js',
                    'mocha',
                    'core-js/es7/reflect',
                    'tslib',
                    // 'ts-node',
                    'ts-mocha',
                    'zone-js',
                    'zone.js/dist/zone',
                    /\.(?!(?:jsx?|json)$).{1,5}$/i
                ]
            })
        ]
    }
);
